{'data': None,
 'distances': [[1.1590009927749634,
                1.1611616611480713,
                1.1878514289855957,
                1.2382476329803467,
                1.240909457206726,
                1.2449288368225098,
                1.2620924711227417,
                1.285057544708252,
                1.3149466514587402,
                1.3199065923690796]],
 'documents': [['Sehr geehrte Frau Präsidentin! Liebe Kolleginnen und '
                'Kollegen! Sehr geehrter Herr Lauterbach! Corona ist nicht '
                'vorbei; das stimmt. Dieser Satz wird ja jetzt gerade immer '
                'mantraartig wiederholt, weil bestimmte Kolleginnen und '
                'Kollegen das nicht verstehen wollen.Aber er verdeckt schon '
                'ein Stück weit, dass sich die Pandemie deutlich verändert hat '
                'in den letzten gut zwei Jahren.Deswegen würde ich Sie gern '
                'noch mal kurz mitnehmen in das erste Jahr der Coronapandemie. '
                'Da war ich nicht hier; da war ich selber in der Klinik. Und '
                'da war es tatsächlich so, dass wir sehr viel damit zu tun '
                'hatten, dass uns in der Klinik alle Masken geklaut wurden und '
                'dass nie Desinfektionsmittel da war, bis überall '
                'Sicherheitsdienste standen. Dann gab es irgendwann das '
                'Problem, dass man nicht mehr wusste, welche Patienten man '
                'jetzt noch behandeln durfte und welche nicht. Permanent '
                'fehlten Kollegen in den Dienstplänen.Ich gebe zu: Da hat man '
                'die Debatten hier im Bundestag wirklich nur aus den '
                'Augenwinkeln wahrgenommen. Aber das, was man mitbekommen hat, '
                'war: Da wurde geklotzt und nicht gekleckert. Da war für alles '
                'Geld da.Und es war auch unglaublich spannend, zu sehen\xa0– '
                'obwohl wir alle immer wieder darauf hingewiesen haben, dass '
                'Klinikbetten alleine noch keine Patienten versorgen können, '
                'dass Beatmungsgeräte allein noch keine Patienten versorgen '
                'können\xa0–, dass das der ganz große Schwerpunkt bei den '
                'Coronabeschaffungsmaßnahmen und Zusatzausgaben der ersten '
                'Monate war.Ich sage das deswegen, weil das was mit den '
                'Beschäftigten im Gesundheitswesen gemacht hat. Wenn du '
                'unglaublich viele Lücken im Dienstplan hast und du kommst '
                'abends zum Nachtdienst und du läufst durch einen Flur, der '
                'voller Betten in Originalverpackung steht, die mit Boni der '
                'Bundesregierung beschafft wurden, ohne dass sie jemals in '
                'Benutzung gehen werden, wenn du siehst, das Geld ist da, aber '
                'es ist kein Kollege da, der mit dir zusammen im Nachtdienst '
                'ist, dann macht das etwas mit dir, weil es dir zeigt: Da '
                'werden die falschen Prioritäten gesetzt. Und wenn du morgens '
                'vom Nachtdienst aus der Klinik rauskommst und du fährst nach '
                'Hause und da ist die Coronateststation und du weißt ganz '
                'genau, dass sich da gerade jemand eine goldene Nase verdient, '
                'sich aber an den Tarifverträgen in den Kliniken nichts '
                'geändert hat, dann macht das was mit den Leuten, die im '
                'Gesundheitswesen arbeiten.Deswegen reicht es nicht, denen '
                'heute Danke zu sagen, sondern wir müssen jetzt in die Phase '
                'kommen, wo wir auch die Arbeitsbedingungen im '
                'Gesundheitswesen dramatisch verbessern, und dafür brauchen '
                'wir auch jeden Euro. Denn wir haben die letzten Monate '
                'kontinuierlich Kolleginnen und Kollegen im Gesundheitswesen '
                'verloren.Da ist einfach unglaublich viel schiefgelaufen; das '
                'wissen wir alle. Deswegen müssen wir heute auch kritischer '
                'draufschauen. Es wurde viel Geld mit vollen Händen '
                'ausgegeben: Maskenbeschaffung, Coronateststationen, diese '
                'Bettenzuschüsse à 50\u202f000\xa0Euro, FFP-Masken-Ausgabe '
                'über die Apotheken. Da ist unglaublich viel schiefgelaufen, '
                'und das muss jetzt vorbei sein.Ja, wir wollen Corona beenden, '
                'und wir wollen alles, was notwendig ist in dieser Krise, '
                'ausfinanzieren. Aber wenn wir kritisch auf alles '
                'draufschauen, was jetzt im Einzelplan drinsteht, dann '
                'geschieht das nicht, weil wir Corona nicht beenden wollten, '
                'sondern weil wir wissen, dass die Mittel in diesem Etat\xa0– '
                'jeder Euro, den man dafür finden kann, dass sich die '
                'Gesundheitsbedingungen und die Arbeitsbedingungen der '
                'Beschäftigten verbessern und ebenso die '
                'Patientenversorgung\xa0– dort noch besser aufgehoben sind. '
                'Das ist der einzige Grund, warum wir so kritisch '
                'draufschauen. Und ich glaube, im dritten Jahr der '
                'Coronapandemie muss man das auch erreichen können.Und damit '
                'kommen wir zum Grundproblem. Eigentlich sollten wir in der '
                'Haushaltsdebatte bei dem Einzelplan\xa015 gar nicht so viel '
                'Ausgabenkritik an der GKV machen. Aber warum müssen wir das '
                'machen? Weil wir jetzt quasi eine teilweise steuerfinanzierte '
                'gesetzliche Krankenversicherung haben. Wir sind als Grüne '
                'Fans der Bürgerversicherung, ja. Aber so ein teilweise '
                'steuerfinanziertes Versicherungskonzept ist nicht unsere '
                'Idee. Das ist absurderweise eines der Vermächtnisse von Jens '
                'Spahn im Gesundheitsministerium, und davon müssen wir ganz '
                'schnell wieder wegkommen.Aber wenn es jetzt schon so ist\xa0– '
                'und es sieht ja eher so aus, als ob das immer weitergeht\xa0'
                '–, dann ist es nur folgerichtig, dass auch das '
                'Bundesfinanzministerium mit in den Schätzerkreis reingenommen '
                'werden muss, und dann ist es auch nur folgerichtig, dass auch '
                'der Haushaltsausschuss in die Ausgabenkritik der GKV '
                'einsteigen muss. Ich halte das aber nicht für ideal, schon '
                'allein, weil dann Kollegen wie Herr Mattfeldt im schlimmsten '
                'Fall mit darüber entscheiden, was im GKV-System noch '
                'finanziert wird und was nicht. Nichts gegen den Kollegen '
                'Mattfeldt, aber das ist keine ideale Lösung.– Na ja, das '
                'bezweifle ich halt.Ich habe jetzt ungefähr dreimal betont, '
                'wie wichtig bessere Arbeitsbedingungen im Gesundheitswesen '
                'sind. Natürlich gibt es in diesem Etatentwurf den '
                'Coronabonus; da steht 1\xa0Milliarde Euro drin, man kann das '
                'machen. Aber es sollte sich niemand der Illusion hingeben\xa0'
                '– wir hatten ja schon Coronaboni in der Vergangenheit\xa0–, '
                'dass wegen so einem Coronabonus jemand, der nach fünf '
                'Nachtdiensten in Folge völlig ausgebrannt ist und sich fragt, '
                'ob er in dieser Art und Weise diesen Beruf in Vollzeit bis '
                'zur Rente durchsteht, nicht in Teilzeit geht oder '
                'irgendjemand zusätzlich im Beruf bleibt. Und auch deswegen '
                'sage ich wieder: Ja, man kann das machen, aber die Frage ist: '
                'Was hätten wir mit dieser Milliarde gegebenenfalls auch an '
                'Verbesserungen für die Arbeitsbedingungen erreichen '
                'können?Ja, die Pandemie ist nicht vorbei. Aber die Zeit der '
                'wenig zielgerichteten Coronamaßnahmen und der Verschwendung '
                'bei den Coronamaßnahmen muss vorbei sein. Wir brauchen jetzt '
                'eine sehr gute Kommunikation zwischen Haushaltsausschuss und '
                'dem Bundesgesundheitsministerium, damit wir eine sehr gute '
                'gemeinsame Grundlage dafür schaffen, was wir in diesem '
                'dritten Jahr der Coronapandemie zielgerichtet finanzieren '
                'können und was nicht.Wir brauchen jeden Euro, den wir '
                'zusätzlich finden können, für eine solide, zukunftsfeste '
                'Aufstellung unseres Gesundheitswesens, das gerade echt auf '
                'dem Zahnfleisch geht. Wir brauchen mehr Mittel für eine echte '
                'Prävention.Da reiße ich jetzt noch mal die Punkte an, die im '
                'Koalitionsvertrag stehen und die sich alle noch nicht im '
                'Haushalt des Ministeriums abbilden.',
                'Geschätzter junger Kollege Banaszak,wir beide mögen uns ja '
                'sehr; aber jetzt diskutieren wir über den Einzelplan\xa009. '
                'Ich freue mich, dass Sie den Energie- und Klimafonds '
                'ansprechen; denn dadurch habe ich noch ein bisschen mehr '
                'Munition; dafür hatte ich in meiner Rede keine Zeit. Dieser '
                'Energie- und Klimafonds stellt demnächst 200\xa0Milliarden '
                'Euro zur Verfügung für Bereiche, die unter Corona nicht '
                'leiden.Das sind Bereiche, die sowieso schon extrem gut '
                'ausgestattet sind. Wenn wir mit dem Energie- und Klimafonds '
                'vernünftig investieren, sind wir auf Ihrer Seite.Wenn wir in '
                'diesen Haushalt hineinschauen, dann könnte man meinen, Herr '
                'Habeck ist nur Klimaschutzminister. Aber Herr Habeck ist auch '
                'Wirtschaftsminister einer der größten Volkswirtschaften der '
                'Welt, nicht nur Klimaschutzminister,und er kürzt Mittel für '
                'den Mittelstand, für die Industrie, für das Handwerk und für '
                'den Handel. Das findet sich hier wieder. Das sind Bereiche, '
                'die das Rückgrat unserer Wirtschaft darstellen; die können '
                'Sie nicht kaputtmachen.Das sehen wir in diesem Haushalt. '
                'Deshalb ganz deutlich: Wir grätschen da rein, wo es '
                'erforderlich ist, und hier ist es erforderlich. Man kann '
                'diese Industriezweige nicht kaputtsparen. Das geht einfach '
                'nicht.Deshalb sage ich: Die Kürzung bei der DZT ist ein '
                'Schlag ins Gesicht für die Mitarbeiterinnen und Mitarbeiter, '
                'die mehr als manch andere unter der Coronakrise gelitten '
                'haben. Es hätte sich gehört, Herr Minister Habeck, diesen '
                'Etat richtig aufwachsen zu lassen, statt ihn zu kürzen. Ich '
                'finde, das ist beschämend. Ich darf schon jetzt ankündigen: '
                'Wir werden dazu einen sehr klugen Antrag vorlegen. Wie ich '
                'Sie kenne, werden Sie sich den zu Gemüte führen; wir beide '
                'werden darüber sprechen, und ich glaube, dann kommen wir auch '
                'vielleicht zu einer vernünftigen Lösung.Denn Sie werden es '
                'den Mitarbeitern dort nicht erklären können, warum Sie für '
                'diese Branche mit über 2\xa0Millionen Mitarbeitern keinen '
                'zusätzlichen Cent übrig haben, aber gleichzeitig '
                'Klimainvestitionen in Biodiversität und Klimaschutz\xa0– '
                'übrigens ausschließlich im Ausland\xa0– unterstützen wollen. '
                'Das werden die Menschen eben nicht verstehen.Ich habe mich '
                'auch\xa0– das darf ich noch sagen, Herr Habeck\xa0– über den '
                'fast halbierten Ansatz bei den LNG-Bunkerschiffen gewundert. '
                'Ja, die Verringerung hier ist planmäßig. Ja, es handelt sich '
                'hier um die Ausfinanzierung eines Projektes. Aber Sie haben '
                'es ja selber angekündigt: LNG ist die Herausforderung.\xa0– '
                'Hier kein Anschlussprojekt anzudocken, ist fast schon '
                'fahrlässig. Auch bei Energiespeichern hätte ich mir etwas '
                'gewünscht. Hier brauchen wir doch jetzt Haushaltansätze. Hier '
                'fehlen die Ansätze; wir Norddeutschen sagen: Wir haben hier '
                'noch bannig Luft nach oben.\xa0– Ich glaube, hier sollten wir '
                'noch nacharbeiten.Aber, Herr Minister, ich will nicht nur '
                'meckern; ich möchte auch loben. Es ist vernünftig, was Sie im '
                'Bereich der Luft- und Raumfahrt gemacht haben. Sie führen das '
                'fort, was wir bereits in der letzten Legislaturperiode '
                'gemacht haben. Das ist klug. Ich habe mich auch gefreut, dass '
                'Sie bei der Erschließung von Auslandsmärkten die Mittel um '
                '145\xa0Millionen Euro angehoben haben. Ähnliches gilt auch '
                'für den Bereich Wasserstoff. Auch hier haben Sie den von der '
                'alten Regierung eingebrachten Mitteln noch einmal einen '
                'Aufwuchs zuteilwerden lassen. Auch das ist eine kluge '
                'Sache.Herr Minister Habeck, Sie haben jetzt in den Beratungen '
                'Zeit, gemeinsam mit uns Parlamentariern aus diesem Entwurf '
                'etwas Vernünftiges zu machen. Sie wissen, dass Sie mich als '
                'Ihren Hauptberichterstatter bei guten Ideen an Ihrer Seite '
                'finden, übrigens alle Berichterstatter für Ihren '
                'Haushaltsentwurf. Vielleicht einen Satz zum Abschluss, Herr '
                'Habeck: Läuft die Wirtschaft, dann läuft es auch mit dem '
                'Klimaschutz.\xa0– In diesem Sinne freue ich mich auf tolle '
                'Beratungen in den kommenden Wochen. Ich bin gespannt, was '
                'dabei herauskommt.Herzlichen Dank.',
                '– das steht aber auch in einem aktuellen Papier Ihres '
                'Koalitionspartners FDP. Das sind kluge Worte, denen Sie '
                'folgen sollten, Herr Minister.Vielen Dank.',
                'Frau Präsidentin! Meine Damen und Herren! Ich darf zunächst '
                'meinem Kollegen Gero Hocker, der hier eigentlich stehen '
                'sollte, gute Genesung wünschen. Alles Gute, Gero!Liebe '
                'Kolleginnen und liebe Kollegen, wir alle wissen, die '
                'Kornkammer in Europa brennt und der Ukrainekrieg hat nicht '
                'nur schwere Folgen für die Energieversorgung, sondern auch '
                'für die Lebensmittelversorgung. Die Getreidepreise steigen '
                'ins Unermessliche\xa0– das haben wir gehört\xa0–, und wo in '
                'Zukunft das Sonnenblumenöl herkommen soll, ist fraglich; '
                'derweil ist auch der heimische Anbau von Ölsaaten stark '
                'rückläufig. Da haben wir noch einiges zu klären.Schon heute '
                'ist klar, dass die Strategie in der Landwirtschaft und in der '
                'Ernährungspolitik\xa0– da sind wir uns alle einig\xa0– '
                'überdacht werden muss.Ein Verzicht auf ungefähr 13\xa0Prozent '
                'der Produktion\xa0– das wäre die Auswirkung der '
                'Farm-to-Fork-Strategie, die kommen soll\xa0– können wir uns '
                'im Moment nicht erlauben.Ich bin froh, dass Frankreichs '
                'Präsident Macron die Herausforderung erkannt hat und damit in '
                'der Europäischen Union vorangeht. Dem Beispiel sollte '
                'Deutschland folgen. Flächenstilllegungen können wir uns jetzt '
                'weniger denn je erlauben.Es ist ein guter und wichtiger '
                'Schritt, dass der Bundeslandwirtschaftsminister Cem Özdemir '
                'angekündigt hat, ökologische Vorrangflächen für die '
                'Lebensmittelproduktion freizugeben. Aber damit die Maßnahme '
                'nicht wirkungslos bleibt, muss auf diesen Flächen unbedingt '
                'auch Pflanzenschutz zur Anwendung kommen dürfen.Es handelt '
                'sich hier nicht\xa0– das muss ich ausdrücklich sagen\xa0– um '
                'Pflanzengift, es handelt sich um Pflanzenschutz.Ich bin mir '
                'sicher: Der Druck, Flächen zu bewirtschaften, statt sie '
                'stillzulegen, wird mit jedem Tag des Krieges größer. Die '
                'Preise für Lebensmittel steigen massiv. Während wir in '
                'Deutschland nur etwas tiefer in die Tasche greifen müssen, '
                'sind die Menschen in ärmeren Ländern akut von einer '
                'Hungersnot bedroht; die Entwicklungsministerin Frau Schulze '
                'hat bereits eindringlich darauf hingewiesen. Herr Minister, '
                'Sie haben vorhin selbst gesagt, was da auf uns zukommt. Die '
                'Knappheit von Lebensmitteln dürfen wir durch das Festhalten '
                'an überholten, vermeintlich nachhaltigen Strategien nicht '
                'noch weiter befördern.Auch beim Dünger zeigt sich, wie '
                'abhängig wir von den Märkten der Ukraine und Russlands sind. '
                'Deshalb brauchen wir mehr denn je die Tierhaltung, die uns '
                'wertvollen Dünger im Sinne der nachhaltigen '
                'Kreislaufwirtschaft liefert.Die Bundesregierung wird mehr für '
                'die Investitionssicherheit der Betriebe tun, mehr für die '
                'Beschleunigung der Genehmigungsverfahren, und wir werden mehr '
                'für die wirtschaftliche Nachhaltigkeit von Betrieben, vor '
                'allem auch in der Tierhaltung in Deutschland, tun.Meine Damen '
                'und Herren, Herausforderungen gibt es nicht nur in der '
                'Landwirtschaft, sondern auch in der Forstwirtschaft. In '
                'Deutschland wird vor allem schnell wachsendes Nadelholz '
                'gebraucht; angepflanzt wird aber überwiegend langsam '
                'wachsendes Laubholz. Gleichzeitig werden Nadelhölzer aus '
                'Russland importiert, was im Moment, aber sicher auch in der '
                'Zukunft nicht mehr möglich sein wird.Die heimische Industrie '
                'spürt bereits jetzt, dass die Nachfrage nach sibirischer '
                'Lärche tot und diese nicht mehr zu bekommen ist. Auch diese '
                'Praxis müssen wir überdenken. Nadelholz muss in unseren '
                'Wäldern mindestens 60\xa0Prozent ausmachen; zum Bauen wird '
                'nun mal Nadelholz gebraucht.Das Thünen-Institut hat '
                'errechnet, dass bei der Fortführung des Waldumbaus bis 2100 '
                'der Nadelholzanteil von heute ungefähr 70\xa0Prozent auf '
                'weniger als 30\xa0Prozent zurückgeht. Es wäre auch ein '
                'fatales Signal, Importe weiter auszuweiten, erst recht aus '
                'Ländern, die den Regenwald demontieren.In Deutschland dürfen '
                'weitere Waldflächen auch nicht stillgelegt werden. Wir '
                'brauchen für einen klimaresilienten Wald ebenso klimarobuste '
                'und nichtheimische Baumarten.– Na ja, der Koalitionsvertrag '
                'ist auch nur ein Papier,das aufgrund einer anderen Weltlage '
                'überarbeitet werden kann.Die Zeitenwende, die wir erleben, '
                'muss die notwendigen Schritte in der Land- und '
                'Forstwirtschaft nach sich ziehen, und wir, die '
                'Bundesregierung, werden daran arbeiten.Vielen Dank.',
                'Sehr geehrte Frau Präsidentin! Liebe Kolleginnen und '
                'Kollegen! Die Haushaltswoche bietet immer eine wunderbare '
                'Gelegenheit, Bilanz zu ziehen, nach hundert Tagen '
                'Ampelregierung ganz besonders. Es ist ein gutes Signal, wie '
                'Sie, Frau Piechotta, es auch formuliert haben, dass das Thema '
                '„Gesundheit und Gesundheitsschutz“ nicht am Geld scheitert. '
                'Was mich aber stört, ist, dass wir in den letzten Wochen und '
                'Monaten nur über das Thema „Pandemie und Covid“ gesprochen '
                'haben.Sosehr ich Sie, lieber Herr Lauterbach, geschätzt habe '
                'in den schwierigen Monaten der Pandemie, wo Sie einen klaren '
                'Kurs gefahren sind, so sehr verzweifle ich momentan an der '
                'Politik in der Pandemie.Sie sorgen weder für Klarheit, was '
                'die Zukunft des Gesundheitssystems angelangt, noch für '
                'Orientierung. Lassen wir die Diskussion über die Impfkampagne '
                'einmal Revue passieren: Wir hatten eine Diskussion darüber\xa0'
                '– die haben Sie angezettelt\xa0–, dass zum Ende des Jahres zu '
                'wenig Impfstoff da wäre. Heute sehen wir, dass Impfstoff auf '
                'Halde liegt. Wir haben eine völlig verquere Debatte über das '
                'Thema Impfpflicht. Es wäre meines Erachtens Ihre Aufgabe '
                'gewesen, einen vernünftigen Plan vorzulegen, abgestimmt mit '
                'den Koalitionspartnern, und nicht das Instrument der '
                'Gewissensentscheidung herbeizureden. Jetzt stehen wir vor den '
                'Scherben dieser Debatte über die Impfpflicht, und es geht '
                'weder vor noch zurück.Auch das Thema Infektionsschutzgesetz '
                'hat Spuren hinterlassen.Aber viel wichtiger ist mir, dass Sie '
                'vom Modus des Pandemieministers endlich in den Modus des '
                'Gesundheitsministers wechseln,dass Sie die Strukturreform '
                'vornehmen, auf die wir alle warten. Das Allerwichtigste ist, '
                'dass Sie uns einen Vorhabenplan vorlegen. Unter Minister '
                'Spahn wussten wir für ein Jahr genau, was an Gesetzesvorhaben '
                'kommen soll. Bisher steht da bei Ihnen auf der Habenseite '
                'nichts.Sie haben vor Kurzem im Bereich Arzneimittel einen '
                'Finanzierungsentwurf vorgelegt, über den es sich wirklich '
                'lohnt zu diskutieren. Da gibt es sicher Elemente, die auch '
                'eine unionsgeführte Regierung eingeführt hätte. '
                'Orphan-Drug-Regelung, Rückwirkung des Erstattungsbetrages, '
                'Bezahlbarkeit von Kombinationstherapien, '
                'Verwurfsproblematik\xa0– das sind alles Dinge, über die es '
                'sich lohnt zu diskutieren. Aber ich gebe ganz offen zu: Ich '
                'halte es für fatal, wenn Sie jetzt im einzigen '
                'Wirtschaftsbereich, der in Deutschland international bestens '
                'positioniert ist, nämlich die Pharmaindustrie\xa0– wir haben '
                'es endlich geschafft, wieder ein Stück weit Apotheke der Welt '
                'zu werden\xa0–, für Verunsicherung sorgen durch Diskussionen '
                'über Herstellerabschlag und Ähnliches. Das ist ein fatales '
                'Zeichen, was die Investitionstätigkeit internationaler '
                'Konzerne angeht. Ich bitte Sie eindringlich, das '
                'zurückzunehmen.Ich will Sie auffordern, endlich deutlich zu '
                'machen, wie es weitergeht mit dem Thema Digitalisierung. Jens '
                'Spahn hat das wunderbar aufs Gleis gesetzt.Ich habe den '
                'Eindruck, dass Sie die Räder wieder zurückdrehen wollen, dass '
                'es im Kern keine elektronische Patientenakte geben soll, kein '
                'E-Rezept. Zu dem ganzen Thema\xa0– wie geht es weiter mit den '
                'Apps? wie können wir Effizienzreserven heben?\xa0– haben wir '
                'bis zum heuten Tage nichts gehört. Das gehört zu Ihren '
                'Aufgaben. Wir als Opposition würden uns gern mit Ihnen '
                'streiten. Aber dafür gibt es zwei Voraussetzungen: Erstens. '
                'Legen Sie Pläne vor! Zweitens und noch viel wichtiger: Kommen '
                'Sie in den Gesundheitsausschuss, um mit uns diese Dinge zu '
                'diskutieren!Herzlichen Dank für Ihre Aufmerksamkeit.',
                'Sehr geehrte Frau Präsidentin! Liebe Kolleginnen und '
                'Kollegen! Herr Minister! Unserem Wald geht es so schlecht wie '
                'nie. Die ökologische und politische Trockenheit der '
                'vergangenen Jahre haben dazu geführt, dass um uns herum, in '
                'Brandenburg, nun schon wieder die zweithöchste Waldbrandstufe '
                'ausgerufen wurde. Das zeigt: Wie in so vielen Bereichen hat '
                'uns die Union infolge ihrer fehlgeleiteten Klimapolitik eine '
                'waldpolitische Kahlschlagfläche hinterlassen.Als Ampel stehen '
                'wir hinter den Waldeigentümerinnen und ‑eigentümern, die '
                'ihren Wald zu einem klimastabilen und artenreichen Mischwald '
                'umbauen. Wir wollen in diesem Jahr 200\xa0Millionen Euro '
                'bereitstellen, um diejenigen zu honorieren, die die '
                'Ökosystemleistung des Waldes, also den Beitrag der Wälder zu '
                'Klima-, Hochwasser-, Trinkwasserschutz und vielem mehr, durch '
                'eine nachhaltige Bewirtschaftung voranbringen. Wir wollen '
                'motivieren, gemeinsam für den Wald anzupacken. Und auch bei '
                'der geplanten Novelle zum Bundeswaldgesetz gilt für uns das '
                'Motto: Regeln, nicht um zu verhindern, sondern um zu '
                'ermöglichen.Meine Damen und Herren, tagtäglich setzen sich '
                'Förster, Jägerinnen, Waldeigentümer und Naturschützerinnen '
                'für das Beste in unseren Wäldern ein; nur die politischen '
                'Mehrheiten in diesem Lande hatten den Wald aus den Augen '
                'verloren. In den vergangenen 30\xa0Jahren wurden 60\xa0'
                'Prozent des Forstpersonals in Deutschland abgebaut; '
                'zeitgleich verdoppelte sich die Rehwildpopulation in unseren '
                'Wäldern. Das Wild gehört zum Wald wie die Butter aufs Brot. '
                'Nur ist es wie so oft im Leben: Trägt man zu dick auf, wird '
                'es irgendwann ungesund.Dass jedes Jahr Hunderte Millionen '
                'Euro Fördergelder, die für das Bäumepflanzen in den Wäldern '
                'ausgeschüttet werden, häufig direkt in den Mägen von '
                'Wildtieren landen, ist nichts anderes als '
                'Steuergeldverschwendung.Lassen Sie uns also gemeinsam dafür '
                'eintreten, dass die gepflanzten Bäume erfolgreich aus dem '
                'Äser heraus- und zum Wald der Zukunft '
                'heranwachsen.Kolleginnen und Kollegen, Putins furchtbarer '
                'Krieg trifft die Menschen in der Ukraine hart. Die wichtigen '
                'und richtigen Sanktionen treffen am Ende auch den Holzmarkt. '
                'Das zeigt einmal mehr, wie wichtig es ist, in der Holz- und '
                'Sägeindustrie regionale Wirtschaftskreisläufe zu stärken. Die '
                'Ampel verfolgt genau dieses Ziel und wird mit einer '
                'Holzbauinitiative vor Ort die langlebigere Nutzung des '
                'wertvollen Klimarohstoffs Holz voranbringen.Lassen Sie uns '
                'gemeinsam für den Wald eintreten; er braucht uns mehr denn '
                'je.Ich danke Ihnen.',
                'Herr Präsident! Liebe Kolleginnen und Kollegen! Heute können '
                'wir mit Freude endlich den ersten Haushalt für Bildung und '
                'Forschung beraten, der mehr Chancengerechtigkeit, '
                'Innovationsfreude und Zukunftsmut atmet.Was wir heute klug '
                'investieren, zahlt sich morgen doppelt und dreifach aus.Wir '
                'leben in einer Zeit multipler Krisen: Krieg, '
                'Klimakatastrophe, Pandemiekrise. Wissenschaft und Forschung '
                'sind Frühwarnsysteme und helfen uns, diese und andere Krisen '
                'zu bewältigen. Würden alle gleichermaßen auf die Wissenschaft '
                'hören, dann wäre für Krisenvorsorge so viel '
                'gewonnen.Missionsorientierte Forschung, Forschung für Klima, '
                'Energie, Frieden, Migration und Gesundheit sind kein '
                'Nice-to-have, sondern elementar für die Resilienz und '
                'Robustheit unserer Gesellschaft.Bildung und Forschung sind '
                'die Quellen unseres künftigen Wohlstands, Wachstums und '
                'Fortschritts, und darum müssen sie gerade jetzt besser '
                'finanziert werden. Wenn wir die 2020er-Jahre zum Jahrzehnt '
                'der Zukunftsinvestitionen machen wollen, muss sich das unter '
                'anderem in unserem Einzelplan\xa030 widerspiegeln, und das '
                'tut es.16 lange Jahre haben Ministerinnen der Union\xa0– Frau '
                'Schavan, Frau Wanka und Frau Karliczek\xa0– das BMBF '
                'geleitet. Ein Wechsel an der Hausspitze tat gutund sorgt für '
                'frische Luft und mit den Projekten des '
                'Ampelkoalitionsvertrags für neuen Drive.Jeder Euro, der in '
                'diesen Haushalt fließt, wird zum Zukunftseuro, wenn wir damit '
                'für Bildung für alle, für Freude am Forschen und für einen '
                'nachhaltigen und klimaneutralen digitalen Umbau unserer '
                'Volkswirtschaft sorgen. Darum bin ich froh, dass der '
                'Regierungsentwurf schon jetzt eine ordentliche Schippe auf '
                'den alten Entwurf der GroKo drauflegt. Bis 2025 werden es '
                'über 4\xa0Milliarden Euro mehr werden\xa0– für Schulen, '
                'Hochschulen, Azubis, Studis, Labore und forschende '
                'Unternehmen.Zentrale Projekte gleisen wir 2022 auf. Mit dem '
                'Programm „Startchancen“ für mehr Bildungsgerechtigkeit werden '
                'wir Schulen in benachteiligten Regionen und Quartieren '
                'unterstützen.Der DigitalPakt bekommt ein Update, um unsere '
                'Schulen endlich für Lehren und Lernen im digitalen Zeitalter '
                'fit zu machen, und die überfällige Modernisierung des BAföG '
                'läuft jetzt an.Wir werden es in mehreren Reformschritten zu '
                'einem Chancengerechtigkeitsgesetz entwickeln.Ich höre von den '
                'Oppositionsbänken jetzt schon wieder, dass das alles noch '
                'nicht reicht. Ist ja klar: In 100\xa0Tagen kann nicht alles '
                'anders, aber vieles besser werden.Ich wünsche mir: Lassen Sie '
                'uns wettstreiten um die besten Konzepte! 100\xa0Tage ohne '
                'Oppositionsanträge: Da fehlt uns was.Lassen Sie uns gern '
                'zusammenwirken, damit Deutschland ein agileres Land der Ideen '
                'wird, mit Chancen für alle, egal welcher Herkunft, von der '
                'Kita bis zur Weiterbildung, mit Offenheit für Neues, mit '
                'Strategien zur Fachkräftesicherung, mit besseren '
                'Arbeitsbedingungen in der Wissenschaft und mit mehr Dynamik '
                'im Innovationsprozess.Gerade als Ausschussvorsitzender bin '
                'ich optimistisch, dass wir als selbstbewusstes Parlament auch '
                'diesen Haushalt an notwendigen Stellen noch besser machen '
                'werden.Wichtig wird auch der Ergänzungshaushalt sein, mit dem '
                'wir auf den russischen Angriffskrieg reagieren; denn '
                'Hunderttausende Schüler/-innen, Studierende und Forschende\xa0'
                '– ukrainische sowie aus Drittstaaten\xa0– müssen vor Krieg '
                'fliehen. Ihre Aufnahme ist eine Mammutaufgabe für unser '
                'Bildungs- und Forschungssystem.Wissenschaftsfreiheit und '
                'weltweite wertegeleitete Wissenschaftskooperationen zeichnen '
                'uns als Land aus. Daher ist das Einfrieren institutioneller '
                'Kooperationen mit dem Putin-Regime so wichtig.Wir können auf '
                'viele Programme und Erfahrungen aus 2015 folgende '
                'zurückgreifen. Wir können die Verfolgtenprogramme aufstocken, '
                'und die Programme „Welcome“ und „Integra“ sind Blaupausen für '
                'jetzt.Die Hilfsbereitschaft hier im Land ist derzeit '
                'riesengroß\xa0– an Schulen, in Ausbildungsbetrieben und an '
                'Hochschulen, von der HRK über den ZDH bis zum DAAD. Danke an '
                'alle, die sich engagieren!Ich wünsche mir in einer Zeit, in '
                'der uns der Krieg auf der Seele liegt und Corona noch in den '
                'Knochen steckt, eine neue Kultur der Zusammenarbeit, vor '
                'allem zwischen Bund, Ländern und Kommunen, im Sinne eines '
                'kooperativen Bildungsföderalismus und einer '
                'Verantwortungsgemeinschaft für bessere Bildung. Sei es die '
                'Aufnahme von Geflüchteten, die Bewältigung der Coronafolgen, '
                'die überfällige Modernisierung unserer Bildungseinrichtungen, '
                'die technologische Souveränität Europas oder die '
                'klimagerechte Transformation: Die Herausforderungen sind '
                'riesig und in den letzten Jahren angewachsen. Sie dulden '
                'keinen Aufschub. Mit diesem Haushalt ist ein wichtiger '
                'Schritt getan.Ich freue mich auf die Beratungen für mehr '
                'Zukunftsmut und mehr Zukunftsinvestitionen.',
                'Sehr geehrte Frau Präsidentin! Kolleginnen und Kollegen! Als '
                'Techniker bin ich es gewohnt, in Gesamtprozessen vom Anfang '
                'bis zum Ende zu denken. Das ist auch in der Wirtschaft\xa0– '
                'gerade bei der Energie\xa0– erforderlich. Das BMWK macht das '
                'leider nicht.Ein Beispiel: Durch Spekulation explodieren die '
                'Energiekosten. Die Glashersteller geraten unverschuldet in '
                'Not; vielen droht die Insolvenz. Ohne Glas gibt es aber nicht '
                'nur keine Glasflaschen, sondern auch keine Fenster für die '
                'energetische Sanierung, keine Ampullen für Medikamente und '
                'auch keine Glasfasern für schnelles Internet.Wenn die '
                'Glasindustrie in Schwierigkeiten schlittert, dann liegt das '
                'auch daran, dass diese Koalition an den Symptomen '
                'herumdoktert, statt Lösungen anzubieten. Sie prüfen '
                'Liquiditätshilfen. Das reicht nicht. Das ist genauso '
                'unzureichend wie die Unterstützung für Menschen mit niedrigem '
                'Einkommen.Gleichzeitig kletterten die Erlöse für EON trotz '
                'Corona von 41\xa0Milliarden Euro im Jahr 2019 auf 77\xa0'
                'Milliarden Euro im Jahr 2021. Für RWE stiegen sie im gleichen '
                'Zeitraum von 13,6\xa0Milliarden Euro auf 24,8\xa0Milliarden '
                'Euro.Und die Profite klettern weiter.Die Linke fordert, gegen '
                'diese Spekulationen vorzugehen. Wir brauchen eine '
                'Preisaufsicht und eine Preisfestsetzung nach '
                'Herstellkosten.Diese Extraprofite müssen dringend abgeschöpft '
                'werden. Dieses Geld benötigen wir für sozial gerechte '
                'Energiekosten für die Menschen und für tragbare Energiepreise '
                'für die Unternehmen\xa0– auch für die Glasindustrie in '
                'Thüringen und Franken.Kolleginnen und Kollegen, nur der '
                'Ausbau von erneuerbaren Energien schützt uns zukünftig vor '
                'Preisexplosionen bei Erdgas und Erdöl.Jeder Kubikmeter Erdgas '
                'und jeder Liter Erdöl, die Deutschland nicht braucht, senken '
                'die Einnahmen von aggressiven Autokraten. Von Russland bis '
                'Arabien gibt es dann weniger Geld zum Waffenkauf.10\xa0'
                'Milliarden Euro mehr für die Energiewende bedeuten mehr '
                'soziale Gerechtigkeit und bringen mehr für den Klimaschutz '
                'und deutlich mehr für die internationale Sicherheit als '
                '100\xa0Milliarden Euro für die Aufrüstung.Vielen Dank.',
                'Frau Präsidentin! Liebe Kolleginnen und Kollegen! Ich kann '
                'nur sagen: Es freut einen Gesundheitspolitiker, wenn man '
                'sieht, welchen beachtlichen finanziellen Einzelplan wir hier '
                'haben, der ein enormes Potenzial entfalten könnte.Herr '
                'Lauterbach, ich möchte ganz kurz Ihre Rede zum Anlass nehmen, '
                'um zu sagen: Ja, es ist klug, vorsichtig zu sein; darüber '
                'brauchen wir überhaupt nicht zu reden. Ich finde es aber '
                'genauso klug, dass man reagiert, wenn man einen Virus kennt '
                'und einen passgenauen Impfstoff hat. Deshalb halte ich das '
                'Vorsorgegesetz der Union für richtig.Meine sehr geehrten '
                'Kolleginnen und Kollegen, dieser milliardenschwere Finanzplan '
                'bedeutet nicht automatisch, dass wir Veränderungen erreichen. '
                'Diese Veränderungen sind im Koalitionsvertrag ja klar '
                'skizziert. Eines ist aber klar: Am Anfang steht eine Idee, '
                'dann benötigt man Geld, und dann muss man in die Umsetzung '
                'kommen. Das ist das, was jetzt Ihre Aufgabe ist.Es wurden das '
                'GKV-System, die Pflegeversicherung und dergleichen '
                'angesprochen; die beiden Kolleginnen von den Grünen, Kollegin '
                'Klein-Schmeink und Frau Dr.\xa0Piechotta, haben das '
                'angemerkt. Man sprach hier von einem heruntergewirtschafteten '
                'System und dergleichen.Diese Meinung teile ich nicht.Sie '
                'haben uns über Jahre erzählt, die Bürgerversicherung wäre die '
                'Lösung. Wenn unser System so schlecht ist, kann ich Sie nur '
                'eines fragen: Warum haben Sie es dann nicht umgesetzt?Sie '
                'sind jetzt in der Regierung. Hätten Sie diesen Systemwechsel '
                'doch gemacht!Sie hatten nicht den Mut, und vielleicht wissen '
                'Sie auch, dass es falsch wäre.Ich möchte hier die Punkte '
                'anbringen, die mir besonders wichtig sind, zum Beispiel\xa0– '
                'das ist klar\xa0– die Pflege und der Dreiklang aus '
                'Pflegebedürftigen, Angehörigen und Mitarbeiterinnen und '
                'Mitarbeitern. Herr Minister, ich kann Ihnen nur sagen: 100\xa0'
                'Tage sind jetzt vergangen. Das, was Sie hier für die Pflege '
                'auf den Weg gebracht haben, ist ein Murks beim Pflegebonus '
                'und eine einrichtungsbezogene Impfpflicht. Das schadet dem '
                'System in meinen Augen, weil es Menschen arbeitslos macht und '
                'die Ressourcen in der Pflege noch weiter schwächt.Es wurde '
                'auch immer vom „Pflegereförmchen“ geredet, das wir auf den '
                'Weg gebracht haben. Ich kann nur sagen: Bisher sehe ich '
                'nichts, was in der Pflege wirklich in die Richtung gehen '
                'würde, dass die Dinge, die Sie vorher angekündigt haben, auch '
                'umgesetzt werden. Das ist in meinen Augen schwach. '
                'Ankündigungen reichen nicht.Das Gleiche gilt für die Kinder- '
                'und Jugendmedizin. Wir finden hier kein Wort darüber.',
                'Frau Präsidentin! Liebe Kolleginnen und Kollegen! Heute vor '
                'einer Woche hat Präsident Selenskyj hier zugeschaltet im '
                'Bundestag gesprochen. Er hat gesprochen von Bomben und '
                'Raketen auf Wohnungen, auf Krankenhäuser, auf Kindergärten, '
                'auf Schulen. Er hat gesprochen von Nord Stream\xa02; er hat '
                'in diesem Zusammenhang den Ausdruck gebraucht, das sei Zement '
                'für eine neue Mauer zwischen Freiheit und Unfreiheit in '
                'Europa. Er hat an unsere historische Verantwortung für die '
                'Ukraine appelliert. Diese Worte des frei gewählten '
                'Präsidenten der Ukraine, überfallen von Putin mit einem '
                'schrecklichen Krieg, wiegen schwer. Sie treffen unser Herz, '
                'unser Gewissen, und sie dürfen nicht folgenlos bleiben.Wir '
                'alle müssen uns fragen: Was hätten wir früher mehr tun '
                'müssen? Wie müssen wir jetzt Konsequenz zeigen? Und: Was '
                'können wir mehr tun? Die Antworten sind nicht einfach.Aber '
                'eines möchte ich mit Blick auf die Ankündigung Putins von '
                'gestern, mit Blick auf die Sanktionierung der russischen '
                'Zentralbank sagen\xa0– dabei habe ich das unermessliche Leid '
                'der Menschen in Mariupol und an vielen anderen Orten in der '
                'Ukraine vor Augen\xa0– : Wir dürfen in dieser Situation nicht '
                'hinter unsere eigenen Beschlüsse zurückgehen und unsere '
                'eigenen Sanktionen unterlaufen.In einer anderen '
                'Konstellation, aber auch schweren Lage hat Helmut Schmidt als '
                'Bundeskanzler gesagt: „Der Staat darf sich nicht erpressen '
                'lassen.“ Heute gilt: Das freie Europa darf sich nicht '
                'erpressen lassen. Deshalb, Herr Minister und sehr geehrte '
                'Damen und Herren der Bundesregierung, braucht es hierauf '
                'jetzt eine klare, eine gemeinsame, eine europäische Antwort. '
                'Diese erwarten wir von den Beratungen der nächsten Tage.Der '
                'richtige Weg ist, alles zu tun, um von russischen Importen '
                'bei der Energie unabhängig zu werden. Herr Minister, auf '
                'diesem Weg haben Sie unsere ausdrückliche Unterstützung. Das '
                'ist unser Weg. Es ist richtig, das jetzt genau so zu tun. Ja, '
                'dafür haben wir eine gemeinsame Grundlage, nämlich den '
                'Beschluss des Bundestages, Klimaneutralität bis 2045 zu '
                'erreichen. Dieser wurde nach der Entscheidung des '
                'Bundesverfassungsgerichts von der Großen Koalition gefasst '
                'und nun von der Ampel übernommen. Jetzt geht es darum, '
                'Energiesicherheit und Klimaschutz zusammenzubringen. Deshalb '
                'ist es notwendig, den Weg, den wir eingeschlagen haben, '
                'weiterzugehen, nämlich Ausbau der erneuerbaren Energien\xa0– '
                'da darf es keinen Stillstand geben; dieser muss massiv '
                'beschleunigt werden\xa0–,die Steigerung der Energieeffizienz, '
                'die Fortführung der Wasserstoffstrategie. Das ist die '
                'eigentliche Antwort, das muss beschleunigt werden.In diesem '
                'Sinne unterstützen wir auch das Oster- und das Sommerpaket. '
                'Wir werden uns die Inhalte genau anschauen. Wir werden eigene '
                'Vorschläge machen. Aber dieses Ziel unterstützen wir. Wenn '
                'gute Vorschläge gemacht werden in dem Sinne, wie Sie es '
                'beschrieben haben, wenn die Kraft der Natur und die Stärke '
                'des Marktes zusammengebracht werden, dann werden wir das mit '
                'Überzeugung im Bundestag unterstützen.Neben Oster- und '
                'Sommerpaket brauchen wir jetzt aber auch ein Winterpaket. Wir '
                'brauchen ein Paket zur Vorsorge für den kommenden Winter. '
                'Dieses muss kurzfristig auf den Weg gebracht werden, und '
                'darin müssen wir Vorsorge treffen bzw. kurzfristig darauf '
                'eine Antwort geben: Wie könnten wir ohne russische Importe '
                'über den nächsten Winter kommen? Das muss jetzt '
                'passieren.Erstens ist es richtig, dazu alles zu unternehmen, '
                'um zusätzliche Kapazitäten zu erschließen und bei anderen '
                'Ländern als Russland einzukaufen, in Europa und weltweit. Das '
                'ist der richtige Weg. Das unterstützen wir.Zweitens. Es ist '
                'richtig, die Konsequenzen daraus zu ziehen, dass unsere '
                'Gasspeicher zu Beginn dieses Winters nicht gefüllt, sondern '
                'zu guten Teilen leer waren. Der Markt hat es hier eben nicht '
                'gerichtet,und das wird so lange gelten, wie Gazprom 20\xa0'
                'Prozent der deutschen Gasspeicher unter seinem Einfluss '
                'hat.Deshalb werden wir als Union morgen im Bundestag den '
                'entsprechenden Gesetzentwurf unterstützen. Da gilt es jetzt, '
                'Konsequenzen zu ziehen.Drittens. Herr Minister Habeck, Sie '
                'haben angemahnt, es müsse auch über Einsparungen gesprochen '
                'werden. Ich sage Ihnen: Wir sind bereit, wenn Sie Vorschläge '
                'machen, ohne Vorfestlegungen mit Ihnen über die Dinge zu '
                'sprechen, die in dieser schweren Situation möglich und '
                'vertretbar sind. Das muss auch\xa0– ohne Vorfestlegung\xa0– '
                'zum Bestandteil des Winterpakets werden. Machen Sie '
                'Vorschläge; wir werden mit Ihnen darüber sprechen. Die '
                'Forderung, es dürfe keine Denkverbote geben, richtet sich '
                'nicht nur an Sie, sondern auch wir wollen sie '
                'beherzigen.Aber\xa0– viertens\xa0– richtet sich die Forderung '
                'eben auch an Sie. Deshalb ist unsere Aufforderung, dass Sie '
                'das tun, was Sie angekündigt haben, nämlich dass Sie '
                'ergebnisoffen und ohne Vorfestlegung prüfen, und zwar auf '
                'Basis des gemeinsamen Bekenntnisses zum Kohlekompromiss und '
                'zum Ausstieg aus der Kernenergie, was in dieser Situation '
                'möglich ist und welche Optionen es gibt, also etwa eine '
                'Modifizierung des Stilllegungspfads bei der Kohle, aber auch '
                'ein möglicher Weiterbetrieb der letzten drei verbliebenen '
                'Kernkraftwerke über den 31.\xa0Dezember hinaus. Ergebnisoffen '
                'und wirklich ohne Vorfestlegung\xa0– das ist unsere '
                'Erwartung.Fünftens. Sie haben über eine Einigung bei den '
                'Entlastungen berichtet. Zur Abfederung der gestiegenen Preise '
                'muss es mehr geben, als bisher vereinbart wurde. Sie haben '
                'jetzt über einige Dinge diskutiert. Wir werden sie bewerten. '
                'Es muss mehr gemacht werden, um die hohen Belastungen von '
                'Bürgern und Betrieben abzufedern. Wenn Sie gute Vorschläge '
                'machen, werden wir Sie dabei unterstützen. Wir haben unsere '
                'eigenen Vorschläge eingebracht. Diese sind nicht so '
                'bürokratisch wie das, was bei Ihnen diskutiert wird. Sie '
                'würden sofort und zielgenau wirken. Das wäre die Basis, um '
                'auch hier zusammenzukommen.Letzte Bemerkung. Wenn Sie so '
                'vorgehen, dann kann gelingen, dass wir\xa0– so wie bei der '
                'Sondersitzung vor vier Wochen\xa0– über die Grenzen von '
                'Regierung und Opposition zu einem breiteren Konsens '
                'zusammenkommen. Mein fester Eindruck ist: In der Lage, in der '
                'wir sind, würde es unserem Land guttun.Vielen Dank.']],
 'embeddings': None,
 'ids': [['8947b0f0-b866-11ef-8aea-ab01e2ceb0cb',
          '8586de46-b866-11ef-8aea-ab01e2ceb0cb',
          '5055a71a-b867-11ef-8aea-ab01e2ceb0cb',
          '7b761858-b867-11ef-8aea-ab01e2ceb0cb',
          '9b74f256-b866-11ef-8aea-ab01e2ceb0cb',
          '84c20c64-b867-11ef-8aea-ab01e2ceb0cb',
          'efb0f9a4-b867-11ef-8aea-ab01e2ceb0cb',
          '7cd53eca-b866-11ef-8aea-ab01e2ceb0cb',
          'a0af5856-b866-11ef-8aea-ab01e2ceb0cb',
          '7a597895-b866-11ef-8aea-ab01e2ceb0cb']],
 'included': ['distances', 'documents', 'metadatas'],
 'metadatas': [[{'date': 1648076400.0, 'speaker': '11005180'},
                {'date': 1648076400.0, 'speaker': '11004108'},
                {'date': 1648076400.0, 'speaker': '11004011'},
                {'date': 1648076400.0, 'speaker': '11004690'},
                {'date': 1648076400.0, 'speaker': '11003551'},
                {'date': 1648076400.0, 'speaker': '11005245'},
                {'date': 1648076400.0, 'speaker': '11003756'},
                {'date': 1648076400.0, 'speaker': '11004091'},
                {'date': 1648076400.0, 'speaker': '11004311'},
                {'date': 1648076400.0, 'speaker': '11003780'}]],
 'uris': None}
